Repository Trippy3/aggregate_pr, pull requests merged in 2023-02, with the labels that each got.

#16 Change to fetching data using GraphQL
  .github/workflows/ci.yml
  .gitignore
  README.md
  __init__.py
  aggregate_pullreq.py
  data/.gitkeep
  modules/date_range.py
  modules/pullreq.py
  modules/repository.py
  modules/tests/test_date_range.py
  modules/tests/test_pullreq.py
  requirements.txt
  tests/__init__.py
  tests/test_aggregate_pullreq.py
Labels: enhancement, breaking

#17 Support for Ghost users
  modules/pullreq.py
  modules/tests/test_pullreq.py
Labels: bug

#18 Feature/#14/duckdb
  .gitignore
  Makefile
  README.md
  aggregate_pullreq.py
  dashboards/.gitkeep
  models/.gitkeep
  modules/database.py
  modules/tests/test_database.py
  requirements.txt
  sources/.gitkeep
Labels: breaking

#19 fix test_pullreq
  aggregate_pullreq.py
  modules/tests/test_pullreq.py
Labels: enhancement

#21 Feature/#20/rill
  README.md
  dashboards/pr_dashboard.yaml
  models/pr_model.sql
  models/sort_readtime.sql
  rill.yaml
  sources/pr.yaml
Labels: documentation, enhancement

#22 fix database
  modules/database.py
Labels: enhancement
